security:
    encoders:
        # this internal class is used by Symfony to represent in-memory users
        Symfony\Component\Security\Core\User\User: auto
        App\Entity\Player: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        players_in_memory:
            memory:
                users:
                    toto:
                        password: '$argon2id$v=19$m=65536,t=4,p=1$4alQx+LKD+tmr4tLei1+gA$Lvq+lkM1UuTs4uL+57Sp/iC53dGjkT4NHIZNzR9hHAQ'
                        roles: ROLE_PLAYER
                    tata:
                        password: '$argon2id$v=19$m=65536,t=4,p=1$4alQx+LKD+tmr4tLei1+gA$Lvq+lkM1UuTs4uL+57Sp/iC53dGjkT4NHIZNzR9hHAQ'
                        roles: ROLE_TATA
        players_in_db:
            entity:
                class: App\Entity\Player
                property: username
        players:
            chain:
                providers: [players_in_memory, players_in_db]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        fragments:
            pattern: '_fragment'
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: players
            form_login:
                check_path: app_security_login_check
                login_path: app_main_index
                default_target_path: app_game_index
                username_parameter: player_login
                password_parameter: player_secret

            logout:
                path: app_security_logout
                target: app_main_index

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: '^/(%locales_regex%)/game', roles: ROLE_PLAYER }
        # - { path: ^/profile, roles: ROLE_USER }
